### ISSUE TITLE
[5-Avsender] Finne og velge riktig mottakeradresse

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#11]
## Users view

Title: **Finne og velge riktig mottakeradresse**
User role(s): Avsender
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Støtte oppslag i felles adresse- og kapabilitetsregister

```[tasklist]
### Features 
- [ ] Oppslag i mottakerregister som Altinn-tjeneste
- [ ] Valg av mottakere ut fra meldingstype basert på kapabilitet og autorisasjon
- [ ] Integrert adresseregister på tvers av sektorene, samt eventuelt ulike mottakerregistre (eks. politiets nåværende mottakerregister)
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 5_
_Stage: Operation_
_ArchiConceptID: id-68c4cf89eb064043a41faf71dfb96b8c_
_GithubIssueID: I_kwDOKIPKBM5vXjGM_

**Comment by erikhag1** [comment]
Avhengig av kontekst? I mange tilfeller vet avsender hvem som er mottaker
