### ISSUE TITLE
[8-Mottaker] Få gjentatt oversendelse av komplett dokumentsamling på forespørsel

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#14]
## Users view

Title: **Få gjentatt oversendelse av komplett dokumentsamling på forespørsel**
User role(s): Mottaker
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Støtte gjentatt oversendelse av hele dokumentsamlingen

```[tasklist]
### Features 
 - [ ] Resending  av  hele dokumentsamlingen  samlet, på forespørsel fra mottaker (siste versjon)
- [ ] Overendelse av  hele pakken samlet på forespørsel fra andre enn opprinnelige mottakere
- [ ] Valg av tidligere versjoner vs. siste versjon

```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 8_
_Stage: Operation_
_ArchiConceptID: id-f42d6e359c7f40eba1544ad11a5a79d5_
_GithubIssueID: I_kwDOKIPKBM5vXjHf_

**Comment by erikhag1** [comment]
Resending vs. Innhenting; oppdatert versjon 
Bakrgunn for versjonering: Saksgrunnlag på gitt tidspunkt
Alternativ: Vi komuniserre behovet fra mottaker til avsender
