### ISSUE TITLE
[10-Mottaker] Identifisere at det er endringer i mottatte filer

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#16]
## Users view

Title: **Identifisere at det er endringer i mottatte filer**
User role(s): Mottaker
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Spore endringer i motatte filer 

```[tasklist]
### Features 
- [ ] Støtte for versjonsmerking av filer fra avsender
- [ ] Sammenlikne filer for å detekter at det er endringer (hash)
- [ ] Endringslogg per pakke/dokumentsamling
- [ ] Støtte for spørringer mot endringslogg
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 10_
_Stage: Operation_
_ArchiConceptID: id-18f62ded9d494ef8b95a25df5f00ccdc_
_GithubIssueID: I_kwDOKIPKBM5vXjIG_

**Comment by erikhag1** [comment]
Juridiske betenkeligheter?
I stedet: Avsender kan versjomsmerke 
Forsendelseid + påtegningsid?
Verifiser hash
