### ISSUE TITLE
[11-Avsender; Mottaker] Integrasjon med egne  fagsystemer 

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#17]
## Users view

Title: **Integrasjon med egne  fagsystemer **
User role(s): Avsender; Mottaker
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Støtte integrasjon (av Altinn formidling) med avsenders og mottakers  fagsystemer.

```[tasklist]
### Features 
- [ ]  API-er for å understøtte integrasjon
- [ ] Mottaker-API i Dialogporten
- [ ] Standardløsning for integrasjon med sak/arkiv-systemer
- [ ] Andre standardintegrasjoner
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 11_
_Stage: Onboarding_
_ArchiConceptID: id-78cab0d9690946c4b26ed8aea745ddf2_
_GithubIssueID: I_kwDOKIPKBM5vXjIm_

**Comment by erikhag1** [comment]
* Tom Sverre og Ragnar har analysert 
* Altinn Studio har API_er for hver app, mens Dialogporten parametrisreer….
