### ISSUE TITLE
[13-Avsender] Kansellere tidligere forsendelser 

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#19]
## Users view

Title: **Kansellere tidligere forsendelser **
User role(s): Avsender
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Støtte for å kansellere forsendelser

```[tasklist]
### Features 
- [ ] Sporing med merking av hele saken som kansellert
- [ ] Slette mottatt pakkesom ikke er overført til noen mottakere
- [ ] Formidle besljed om kansellering til de som har lastet ned
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 13_
_Stage: Operation_
_ArchiConceptID: id-7894b1b7e3f9484abc7ac64f4d811629_
_GithubIssueID: I_kwDOKIPKBM5vXjOJ_
