### ISSUE TITLE
[16-Avsender] Løpende innsikt i  status om levering, mottak og lesing av forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#22]
## Users view

Title: **Løpende innsikt i  status om levering, mottak og lesing av forsendelser**
User role(s): Avsender
Users value statement(s): 
Å vite nøyaktig når en forsendelse er levert, mottatt eller lest, gjør det lett å følge med på forsendelsen, og resultatet kan brukes som input til å starte andre prosesser og aktiviteter.  Mottakere som venter på viktig informasjon vil sette pris på å kunne få oppdateringer om statusen på sine forsendelser.

## Vendors view

High level features (capabilities):
 * Sanntids sporing av status om levering, mottak og lesing av forsendelser

```[tasklist]
### Features 
- [ ] Logging. NB: Bør være fellesløsning. 
Notifikasjoner/events
- [ ] GUI for sporing av meldinger
- [ ] GUI for saksgang (via Altinn Studio, Dialogporten)?
- [ ] API for å forespørre status (har det i dag for kvitteringer)
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 16_
_Stage: Operation_
_ArchiConceptID: id-e5a01df6c4db4f398541a0f717c414cd_
_GithubIssueID: I_kwDOKIPKBM5vXjPX_

**Comment by erikhag1** [comment]
Sanntids sporing av status om levering, mottak og lesing av forsendelser
