### ISSUE TITLE
[17-Kunde] Minst mulig arbeid og kostnader ved overgang til nye løsninger og grensesnitt i meldingsinfrastrukturen

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#23]
## Users view

Title: **Minst mulig arbeid og kostnader ved overgang til nye løsninger og grensesnitt i meldingsinfrastrukturen**
User role(s): Kunde
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Enkel overgang til ny løsninger  og versjoner

```[tasklist]
### Features 
- [ ] Automatiserte overgangsrutiner (instllasjonsjobber mv.)
- [ ] Referanseimplementasjoner
- [ ] Pekere til gode eksemepler/ god praksis
- [ ] Dokumentasjon, veiledning og kommunikasjon (informasjonsmøter
- [ ] Brøytekjøring sammen med utvalgte kunder og partnere/konsulenter
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 17_
_Stage: Migration_
_ArchiConceptID: id-13d9833c428d4ae88636a41772554305_
_GithubIssueID: I_kwDOKIPKBM5vXjP0_
