### ISSUE TITLE
[20-Avsender ] Oppdage forsinkede  og mislykte forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#26]
## Users view

Title: **Oppdage forsinkede  og mislykte forsendelser**
User role(s): Avsender 
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 *  Feilhåndtering for forsinkede og mislykte forsendelser

```[tasklist]
### Features 
- [ ] Varsle avsender om sen levering ift. SLA
- [ ] Varsle avsender om mislykket levering (med forståelig feilmeldig
- [ ] Registrere resultat av avsenders eventuelle alternative leveringsforsøk (f.eks. på minnepinne)
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 20_
_Stage: Operation_
_ArchiConceptID: id-284f5297ab634d3da4b63089596ff281_
_GithubIssueID: I_kwDOKIPKBM5vXjQ5_
