### ISSUE TITLE
[21-Avsender] Oversikt over tidligere transaksjoner for levering , mottak og lesing av forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#27]
## Users view

Title: **Oversikt over tidligere transaksjoner for levering , mottak og lesing av forsendelser**
User role(s): Avsender
Users value statement(s): 
Å ha en detaljert oversikt over statuser for gjennomførte forsendelser kan være verdifull for revisjonsformål, som juridisk dokumentasjon og som input til å forbedre min tjeneste. 

## Vendors view

High level features (capabilities):
 * Gi oversikt over tidligere transaksjoner for levering, mottak og lesing av forsendelser

```[tasklist]
### Features 
- [ ] Lagring av logg
- [ ] GUI for visning av historikk
- [ ] API - spørring mot logg
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 21_
_Stage: Maintenance_
_ArchiConceptID: id-9e52397b1f51481c9b4e36f153eb4f0a_
_GithubIssueID: I_kwDOKIPKBM5vXjRS_

**Comment by erikhag1** [comment]
Flere grunner, blant annet juridisk - korrekt bevismateriale….
