### ISSUE TITLE
[23-Avsender] Sende filsamlinger med mulighet for samlet og enkeltvis levering og oppfølging av status 

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#28]
## Users view

Title: **Sende filsamlinger med mulighet for samlet og enkeltvis levering og oppfølging av status **
User role(s): Avsender
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Formidle filsamlinger med støtte  for både samlet og enkeltvis levering og oppfølging av status

```[tasklist]
### Features 
- [ ] Pakking av enkeltfiler i større pakker (inkl. signeing av pakken) 
- [ ] Utpakking av enkeltfiler før levering
- [ ] Overføre enkeltfiler i større pakker
- [ ] Levere en og en fil i større pakker

```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 23_
_Stage: Operation_
_ArchiConceptID: id-8a86f7f76bf24c1c9f06b2be758e79d3_
_GithubIssueID: I_kwDOKIPKBM5vXjR9_

**Comment by erikhag1** [comment]
Metadata med if som knytter sammen filer til en samling. Dessuten metadata som muliggjør f.eks. versjonsmerking (enten nasjonal standard, industristandard eller bilaterale avtaler, ev. tjenesteeier)
