### ISSUE TITLE
[24-w] Sende store  filer til en eller flere mottakere 

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#29]
## Users view

Title: **Sende store  filer til en eller flere mottakere **
User role(s): w
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Formidle oversendendelse av store filer fra en avsender til en eller flere mottakere

```[tasklist]
### Features 
- [ ] GUI for avsender 
- [ ] Levere meldinger til adresserte mottakere
' Adressering og ruting basert på adresse/kapabilitetsregister
- [ ] Støtte pub-sub
- [ ] Logging av mottak også for events (ikke for lesing av events for Formidlingstjensten)
- [ ] Event-basert statustilbakemelding
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 24_
_Stage: Operation_
_ArchiConceptID: id-e7b524d5fcc04edabf0db219d0d164fe_
_GithubIssueID: I_kwDOKIPKBM5vXjST_

**Comment by erikhag1** [comment]
Det nye Rressursregisteret/RRR åpner for at tjenesteeiere kan lege inn logikk som f.eks. mottakerregister. Se også ELMA… Kan settes opp av mottaker (hva kan og vil jeg) og/eller tjenesteeier
* ang. pub-sub: push-varsel
* funksjonalitet for å sjekke status på prosess oppp mot koreografi
