### ISSUE TITLE
[27-Kunde] Tilgang til brukerstøtte og veiledning

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#32]
## Users view

Title: **Tilgang til brukerstøtte og veiledning**
User role(s): Kunde
Users value statement(s): 
* Enkelt å bruke løsningen
* Unngå feilsituasjoner
* Raskt å løse opp i feil eller promlemer som eventuelt inntreffer

## Vendors view

High level features (capabilities):
 * Brukerstøtte og veiledning

```[tasklist]
### Features 
- [ ] Brukerdokumentasjon
- [ ] Teknisk support 24*7;)
- [ ] Spesialisttøtte (betalt).
- [ ] Støtte for eLæring
```

```[tasklist]
### Work items
- [ ] Definere opplæringsløp
- [ ] Opprette brukermanual
- [ ] Teknisk dokumentasjon
- [ ] Utvikle FAQ med ofte stilte spørsmål og svar
- [ ] Lag opplæringsvideo/ webinar
- [ ] Finn ut og beslutt gjennomføring av brukerundersøkelser
- [ ] Etabler feedback prosess for forbedring og utvikling av våre produkter
- [ ] Gjennomgang og kvalitetssikre dokumentasjon. Etabler det som fast rutine
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 27_
_Stage: Maintenance_
_ArchiConceptID: id-033cd5c48bb4403f9f55ad3e5ad8090f_
_GithubIssueID: I_kwDOKIPKBM5vXjY7_
