### ISSUE TITLE
[28-Tjenesteeier] Tilrettelegge brukervennlige løsninger for å sende og motta store filer

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#4]
## Users view

Title: **Tilrettelegge brukervennlige løsninger for å sende og motta store filer**
User role(s): Tjenesteeier
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Tilby brukervennlig løsning for å sende og motta store filer

```[tasklist]
### Features 
- [ ] Altinn GUI  for avsender
- [ ]  Drag&drop filer for opplasting
- [ ]  Framdriftsindikator for oppalastiing
- [ ]  Presentasjon av sanntids sporing i avsenders GUI
    - [ ] Hjelp-funksjon i GUI
- [ ]  Altinn GUI for mottaker
    - [ ] Drag&drop filer for nedlasting
    - [ ] Framdriftsindikator for opplastiing
    - [ ] Lesebekreftelse
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 28_
_Stage: Onboarding_
_ArchiConceptID: id-b895cb2c76844c04bbf73edd50528a1b_
_GithubIssueID: I_kwDOKIPKBM5vWZHE_

**Comment by erikhag1** [comment]
Annet enn GUI?
Løsning kan omfatte f.els. Skreddersydd Altinn Studio app
