### ISSUE TITLE
[1-Kunde] Abonnere på tilleggstjenester (arkivering, statistikk mv.) og ønsket grad av tjenestekvalitet (responstid, størrelse, lagringstid mv.)

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#5]
## Users view

Title: **Abonnere på tilleggstjenester (arkivering, statistikk mv.) og ønsket grad av tjenestekvalitet (responstid, størrelse, lagringstid mv.)**
User role(s): Kunde
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * - [ ] Tilby abonnement på relevante  tilleggstjenester og grader av tjenestekvalitet

```[tasklist]
### Features 
- [ ] Oversikt over opsjoner - tilleggstjenster og tjenestekvalitet
- [ ] Produktpakker med standardvalg av opsjoner og SLA-nivåer
- [ ] Service management system/CRM
```

```[tasklist]
### Work items
- [ ] Lag foreløpig oversikt over aktuelle opsjoner og SLA-parametre. Må uasnett gjøres i  ny KS2-runder
- [ ] Juridisk; Ta utgnagspunkt i  samarbeidsavtalen bilag 3
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 1_
_Stage: Onboarding_
_ArchiConceptID: id-091a20689a734200b61439495bfab82a_
_GithubIssueID: I_kwDOKIPKBM5vWZjH_

**Comment by erikhag1** [comment]
Foreløpig liste over tilleggstjenester:
* Skreddersydde rapporter
* Lokasjon for lagring ref. Schrems s II
* Garantert ytelse vha. dedikert maskinvare

NB: Mangler Service management system
