### ISSUE TITLE
[4-Kunde] Lett forståelig og strukturert fakturagrunnlag

### ISSUE THREAD

**Issue by erikhag1** [Altinn/testrepo-melding-formidling#6]
## Users view

Title: **Lett forståelig og strukturert fakturagrunnlag**
User role(s): Kunde
Users value statement(s): 
* Effektiv fakturabehandling
* Mulighet for automatisering av fakturabehandling

## Vendors view

High level features (capabilities):
 * Støtte for effektiv fakturabehandling

```[tasklist]
### Features 
- [ ] Transaksjonslogg
- [ ] Statistikk som viser trend i transaksjonsvolum
- [ ] Spesifisert fakturagrunnlag for manuell behandling
- [ ] Spesifisert fakturagrunnlag for maskinell behandling
- [ ] Samlet faktura fra Digdir/Altinn
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 4_
_Stage: Onboarding_
_ArchiConceptID: id-64613d290c4a42bf807898b4978d5d9f_
_GithubIssueID: I_kwDOKIPKBM5vW1TS_

**Comment by erikhag1** [comment]
Initial comments:

* sadsad
* asdsadd sad

**Comment by erikhag1** [comment]
NB: Ikke kryssfinansierng!
